version: '2'
services:
  influxdb:
    image: tutum/influxdb:latest
    environment:
      PRE_CREATE_DB: "collectd"
      ADMIN_USER: "dbadmin"
      INFLUXDB_INIT_PWD: "dbpassword"
      COLLECTD_DB: "collectd"
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - "${DOCKER_COMPOSE_MOUNT}./var/influxdb:/data"
